jsmode @"\" + currentmacrofilename;

js {

function updateHidemaruVersion() {
    var command_line = sprintf('"%s\\test.bat" "%s" "%s"', currentmacrodirectory(), hidemarudir(), currentmacrofilename());
    var pi = hidemaru.runProcess(command_line, ".", "gui", "sjis");
    hidemaru.postExecMacroMemory("quitall");
}

function showHidemaruReleaseNote() {

    var hmversion = hidemaruversion();
    var regex = /(\d+)\.(\d+)\.(\d+)/;
    var match = hmversion.match(regex);

    if (!match) {
        return;
    }

    var major = Number(match[1]);
    var minor = Number(match[2]);
    var build = Number(match[3]);

    var url = "";

    if (minor == 99 || build == 99) {
        url = "https://hide.maruo.co.jp/software/hidemaruhist.html";

    // それ以外はβバージョン
    } else {
        url = "https://hide.maruo.co.jp/software/hidemaruhist_pre.html";
    }

    browserpanecommand({
        target: "_each",
        initialize: "async",
        url: url,
        show: 1,
        size: 500
    });
}

if (getarg(0) == "show_release_note") {
    showHidemaruReleaseNote();
} else {
    updateHidemaruVersion();
}


} // js

